### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by ksl594303117** [meff34/docsify-to-pdf-converter#37]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/20100608/226855782-be3a72cb-6d93-4280-8cb4-046a2f608c02.png">

**Comment by meff34** [comment]
Thank you for bringing this to my attention. After reviewing the issue, it seems that the package you are looking for is still available on npm. Therefore, the problem may be related to the configuration settings of your nexus registry. I kindly suggest checking your nexus configuration to ensure that everything is properly set up.

If you are interested in checking the availability of the docsify-pdf-converter package, you can visit the following link: https://registry.npmjs.org/docsify-pdf-converter.

When visiting the link, the expected result is to see a JSON response with information about the package, including its name, description, and versions. This indicates that the package is available on the npm registry.

If the package is not available on the npm registry, you may receive a 404 response or an error message indicating that the package does not exist. Alternatively, you may encounter technical issues that prevent you from accessing the npm registry altogether.

Please feel free to reopen this issue if you need further assistance or if you have any other questions related to the package. I'll be happy to help you.
